"""empty message

Revision ID: 5401f0ddcc15
Revises: cb6907cce819
Create Date: 2024-11-06 19:11:04.337362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5401f0ddcc15'
down_revision = 'cb6907cce819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=250), nullable=False),
    sa.Column('scientific_name', sa.String(length=250), nullable=True),
    sa.Column('other_name', sa.String(length=250), nullable=True),
    sa.Column('default_image', sa.String(length=250), nullable=True),
    sa.Column('watering', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('plant-table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant-table',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"plant-table_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('common_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('scientific_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('other_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('default_image', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('watering', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='plant-table_pkey')
    )
    op.drop_table('plants')
    # ### end Alembic commands ###
