"""empty message

Revision ID: 6084065a9698
Revises: 2432d95e9040
Create Date: 2024-11-14 17:37:33.884539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6084065a9698'
down_revision = '2432d95e9040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=250), nullable=False),
    sa.Column('scientific_name', sa.String(length=250), nullable=True),
    sa.Column('other_name', sa.String(length=250), nullable=True),
    sa.Column('default_image', sa.String(length=250), nullable=True),
    sa.Column('watering', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('firstname', sa.String(length=250), nullable=False),
    sa.Column('lastname', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('user')
    op.drop_table('plants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('common_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('scientific_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('other_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('default_image', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('watering', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='plants_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('user_table')
    op.drop_table('plant_table')
    # ### end Alembic commands ###
